services:

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml
    command:
      - "--config.file=/config/blackbox.yml"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
